# Generated by Django 5.0.3 on 2024-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
    ]
